version: "3"
services:
  mysql:
    container_name: mysql-server
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "jouko_api"
      MYSQL_USER: "jouko"
      MYSQL_PASSWORD: "jouko"
    networks:
      - jouko-api-net

  jouko-api:
    container_name: jouko-api
    build:
      dockerfile: ./docker/Dockerfile.api
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mysql

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:16.1.1
    hostname: keycloak
    ports:
      - "9080:9080"
      - "10990:10990"
    command: ["-Djboss.socket.binding.port-offset=1000"]
    volumes:
      - ./dev/:/opt/keycloak/
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - jouko-api-net

  jouko-ui:
    container_name: jouko-ui
    build:
      dockerfile: ./docker/Dockerfile.user-ui
      context: .
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - jouko-api
      - keycloak

  jouko-admin:
    container_name: jouko-admin-ui
    build:
      dockerfile: ./docker/Dockerfile.admin-ui
      context: .
    ports:
      - 8001:8001
    depends_on:
      - mysql
      - jouko-api
      - keycloak
    
networks:
  jouko-api-net:
    driver: bridge