version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "jouko_api"
      MYSQL_USER: "jouko"
      MYSQL_PASSWORD: "jouko"