version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "jouko_api"
      MYSQL_USER: "jouko"
      MYSQL_PASSWORD: "jouko"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
  keycloak:
    image: jboss/keycloak:8.0.29.Final
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8180:8180"
    volumes:
      - ./dev/:/opt/keycloak/
    environment:
      DB_VENDOR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_ADDR: mysql
      DB_PASSWORD: root
  jouko-ui:
    build:
      context:
      dockerfile: Dockerfile.user-ui
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - api
      - keycloak
  jouko-admin:
    build:
      context:
      dockerfile: Dockerfile.admin-ui
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - api
      - keycloak