# Pull the latest LTS version of Node.JS (16.x) and use "as" if want to do production in the future
FROM node:lts-gallium as user-ui

# Create a working directory for the project
WORKDIR /jouko/jouko-user-ui

# Copy jouko-user-ui files to container
COPY jouko-ui .

# Install dependencies
RUN npm install

# Run the development server
CMD ["npm", "run", "start"]