# Pull the latest LTS version of Node.JS (16.x) and use "as" if want to do production in the future
FROM node:lts-gallium as admin-ui

# Clone project as local COPY never compiles
RUN git clone https://github.com/Metatavu/jouko.git jouko

# Change current directory to the cloned project
WORKDIR /jouko/jouko-admin-ui

# Install dependencies
RUN npm install

# Run the development server
CMD ["npm", "run", "start"]