FROM quay.io/keycloak/keycloak:17.0.1-legacy as builder

# Build keycloak
RUN /opt/keycloak/bin/kc.sh build

# Setup a local SSL certificate
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]